package com.example.springdatadynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "Customer")
public class Customer {

    @Id
    private CustomerId customerId;

    private String firstName;
    private String lastName;

    public Customer() {}

    public Customer(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    @Override
    public String toString() {
        return String.format(
                "Customer[id=%s, sortKey=%s, firstName='%s', lastName='%s']",
                customerId.getId(), customerId.getSortKey(), firstName, lastName);
    }


    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return customerId != null ? customerId.getId() : null;
    }

    public void setId(String userName) {
        if (customerId == null) {
            customerId = new CustomerId();
        }
        customerId.setId(userName);
    }

    @DynamoDBRangeKey(attributeName = "SortKey")
    @DynamoDBAutoGeneratedKey
    public String getSortKey() {
        return customerId != null ? customerId.getSortKey() : null;
    }

    public void setSortKey(String playlistName) {
        if (customerId == null) {
            customerId = new CustomerId();
        }
        customerId.setSortKey(playlistName);
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }

    @DynamoDBAttribute
    public String getLastName() {
        return lastName;
    }


    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}